#!/usr/bin/env python3

from PIL import Image
import numpy as np
import sys

if __name__ == '__main__':
    imgPath = sys.argv[1]

    image = Image.open(imgPath).convert("L")
    image = image.resize((256,256))
    array = np.asarray(image,dtype=np.float32)

    fileName = imgPath.split('/')[-1].split('.')[0]
    fileName = fileName+'.bin'
    
    with open(fileName, 'wb') as f:
        f.write(array.tobytes())